name: Acceptance Tests
on:
  pull_request:
    paths-ignore:
      - 'LICENSE'
      - '**.md'
      - 'website/**'
      - 'docs/**'
  push:
    paths-ignore:
      - 'LICENSE'
      - '**.md'
      - 'website/**'
      - 'docs/**'
  schedule:
    - cron: '0 13 * * *'
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2.1.2
      with:
        go-version: '1.13'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2.3.2

    - name: Get dependencies
      run: |
        go mod download
    - name: Build
      run: |
        go build -v .
  test:
    name: Matrix Test
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 240
    strategy:
      fail-fast: false
      matrix:
        version:
          - stable
        terraform:
          - '0.12.29'
          - '0.13.3'
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2.1.2
      with:
        go-version: '1.13'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2.3.2

    - name: Get dependencies
      run: |
        go mod download

    - name: TF acceptance tests
      timeout-minutes: 120
      env:
        TF_ACC: "1"
        TF_ACC_TERRAFORM_VERSION: ${{ matrix.terraform }}

        PACKET_AUTH_TOKEN: ${{ secrets.PACKET_AUTH_TOKEN }}
      run: |
        go test -v -cover -run=TestAccPacketProject_Basic ./packet
